### ISSUE TITLE
Bad srcdoc attribute in noscript iframe

### ISSUE THREAD

**Issue by matej-marcisovsky** [seznam/IMA.js-ui-atoms#25]
If property `srcDoc` is not a string with desired content then displayed content is `null` in non JavaScript browser. There is no control over this attribute passed into noscript tag.

https://github.com/seznam/IMA.js-ui-atoms/blob/master/src/iframe/HtmlIframe.jsx#L107

**Comment by matej-marcisovsky** [comment]
srcdoc attribute can be an empty string => `this.props.srcDoc !== null`

**Comment by mjancarik** [comment]
fixed https://github.com/seznam/IMA.js-ui-atoms/pull/26
